name: Android CI

on:
  pull_request:
    branches-ignore:
      - "l10n_v3_openjdk2"
  push:
    branches-ignore:
      - "l10n_v3_openjdk2"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get gl4es latest commit hash
        if: github.ref == 'refs/heads/v3_openjdk'
        id: gl4es-sha
        run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es refs/heads/master | grep -io '^\S*'))"
壳: 猛敲

      - 名字: Cache gl4es
如果: github.ref =='refs/heads/v3_openjdk'
用途: actions/cache@v2
身份证: gl4es-cache
与:
路径: gl4es/libs
键: gl4es-android-共享-nodbg-test1-2-${{ steps.gl4es-sha.outputs.sha }}

      - 名字: 获得gl4es
如果: github.ref =='refs/heads/v3_openjdk'&& steps.gl4es-cache.outputs.cache-hit !='true'
用途: actions/checkout@v2
与:
仓库: "ptitSeb/gl4es"
路径: "gl4es"

      - 名字: 打造gl4es
如果: github.ref =='refs/heads/v3_openjdk'&& steps.gl4es-cache.outputs.cache-hit !='true'
        continue-on-error: 真正的
跑: |
cd gl4es
git config --global user.email "github-actions@users.noreply.github.com"
git config --global user.name "github-actions"
git remote添加上游https://github.com/PojavLauncherTeam/gl4es
上游
结账主机
git合并-允许-无关-历史上游/主|回声“合并退出代码$？”
$ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk

      - 名字: 安装gl4es
如果: github.ref =='refs/heads/v3_openjdk'&& steps.gl4es-cache.outputs.cache-hit !='true'
        continue-on-error: 真正的
跑: |
cp -R gl4es/libs/* app_pojavlauncher/src/main/jniLibs/
mv gl4es ..
git添加。
git commit -am "CI: Update gl4es"
git推送

      - 名字: 获取最新提交散列
如果: github.ref =='refs/heads/v3_openjdk'
身份证: vgpu-sha
跑: 回声"::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/VGPU refs/heads/main | grep -io '^\S*'))"
壳: 猛敲

      - 名字: 缓存vgpu
如果: github.ref =='refs/heads/v3_openjdk'
用途: actions/cache@v3
身份证: vgpu-cache
与:
路径: vgpu/libs
键: vgpu-android-共享-1-${{ steps.vgpu-sha.outputs.sha }}

      - 名字: 获取vgpu
如果: github.ref =='refs/heads/v3_openjdk'&& steps.vgpu-cache.outputs.cache-hit !='true'
用途: actions/checkout@v2
与:
仓库: "PojavLauncherTeam/VGPU"
路径: "vgpu"

      - 名字: 构建vgpu
如果: github.ref =='refs/heads/v3_openjdk'&& steps.vgpu-cache.outputs.cache-hit !='true'
        continue-on-error: 真正的
跑: |
cd vgpu
$ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk

      - 名字: 安装vgpu
如果: github.ref =='refs/heads/v3_openjdk'&& steps.vgpu-cache.outputs.cache-hit !='true'
跑: |
cp -R vgpu/libs/* app_pojavlauncher/src/main/jniLibs/
mv vgpu ..
git config --global user.email "github-actions@users.noreply.github.com"
git config --global user.name "github-actions"
git添加。
git commit -am "CI: Update vgpu"
git推送

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: QuestCraftPlusPlus/android-openjdk-build-multiarch
          branch: buildjre17
          name: jre17-pojav

      - name: Clean Artifacts Folder
        run: |
          rm -rf app_pojavlauncher/main/src/assets/artifacts/*

      - name: Build APK with Gradle
        run: |
          chmod +x scripts/languagelist_updater.sh
          bash scripts/languagelist_updater.sh

          mkdir -p out
          chmod +x gradlew
          ./gradlew clean
          # Build JRE JAR files (security manager, etc...)
          ./gradlew :jre_lwjgl3glfw:build
          # mkdir app_pojavlauncher/src/main/assets/components/internal_libs
          # rm app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar # removed because causes issues
          # cp jre_lwjgl3glfw/build/libs/jre_lwjgl3glfw-3.2.3.jar app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar # removed because causes issues
          
          # Build the launcher
          ./gradlew :app_pojavlauncher:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app_pojavlauncher/build/outputs/apk/release/app_pojavlauncher-release.apk
